# Generated by Django 2.2.4 on 2019-08-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dumps',
            fields=[
                ('side_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('dump_model', models.CharField(max_length=50)),
                ('max_tonnage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage', models.FloatField()),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Dumps')),
            ],
        ),
    ]
