# Generated by Django 2.2.4 on 2019-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumps',
            name='max_tonnage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='parametrs',
            name='tonnage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
