# Generated by Django 2.2.4 on 2019-08-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20190806_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumps',
            name='max_tonnage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parametrs',
            name='tonnage',
            field=models.FloatField(),
        ),
    ]
