# Generated by Django 2.2.4 on 2019-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20190807_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumps',
            name='max_tonnage',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='parametrs',
            name='tonnage',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
