# Generated by Django 2.2.4 on 2019-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20190807_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumps',
            name='max_tonnage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='parametrs',
            name='tonnage',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
